# Start from the rayproject/2.35.0-py310-aarch64 image for raspberry pi

FROM rayproject/ray:2.35.0-py310

# Install dependencies from requirements.txt
COPY requirements.txt .
RUN pip install -r requirements.txt
