apiVersion: v2
name: NAOMI
description: NAOMI Helm chart for Kubernetes
type: application
version: 0.3.2
appVersion: "0.3.2"

dependencies:
- condition: mlflow.enabled
  name: mlflow
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 5.1.15

- condition: minio.enabled
  name: minio
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.0.21

- condition: flyte-binary.enabled
  name: flyte-binary
  repository: https://flyteorg.github.io/flyte
  version: 1.15.3

- name: kuberay-operator
  repository: https://ray-project.github.io/kuberay-helm/
  version: 1.4.2

- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 76.4.1

