general:
  ip: "<CHANGE-ME>"

#################################################
#
# Ray
#
################################################
rayVersion: "2.48.0"
headGroupSpecs:
  rayHead:
    image: copandrej/ijs-custom:ray-amd64-ray248
    resources:
      limits:
        cpu: "2"
        memory: "6G"
      requests:
        cpu: "2"
        memory: "6G"
        
rayClusterConfig:
  enableInTreeAutoscaling: true

workerGroups:
  amdGroup:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    rayStartParams:
      numCpus: "1"
    container:
      image: copandrej/ijs-custom:ray-amd64-ray248
      resources:
        limits:
          cpu: "1"
          memory: "6G"
        requests:
          cpu: "1"
          memory: "6G"
#      ports:
#        - 9900
#      nodePorts:
#        - 30070

  aarchGroup:
    replicas: 0
    minReplicas: 0
    maxReplicas: 0
    rayStartParams:
      numCpus: "1"
    container:
      image: rayproject/ray:2.48.0 # BUG: can't build the arm image currently so NAOMI on arm doens't work
      resources:
        limits:
          cpu: "1"
          memory: "5G"
        requests:
          cpu: "1"
          memory: "5G"
#      ports:
#        - 9900
#      nodePorts:
#        - 30070

kuberay-operator:
  nodeSelector:
    kubernetes.io/arch: "amd64"

#################################################
#
# MLFlow
#
# mlflow is a subchart, for all possible configurations and values refer to: https://github.com/bitnami/charts/tree/main/bitnami/mlflow/
################################################
mlflow:
  enabled: true
  image:
    repository: bitnamilegacy/mlflow # Fix for bitnami deprecating support for their docker images https://github.com/bitnami/charts/issues/35164
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  waitContainer:
    image:
      repository: bitnamilegacy/os-shell
  gitImage:
    image:
      repository: bitnamilegacy/git
  tracking:
    auth:
      enabled: false
    service:
      type: NodePort
      ports:
        http: 80
      nodePorts:
        http: "31007"
    nodeSelector:
      kubernetes.io/arch: "amd64"
    # externalS3 new
    externalS3:
      host: "minio"
      port: 9000
      accessKeyID: "minio"
      accessKeySecret: "miniostorage"
      protocol: "http"
      bucket: "mlflow"
      serveArtifacts: true
  run:
    nodeSelector:
      kubernetes.io/arch: "amd64"
  minio:
    enabled: false
  postgresql:
    enabled: true
    primary:
      service:
        ports:
          postgresql: 5430
    image:
      repository: bitnamilegacy/postgresql 

#################################################
#
# Minio
#
# minio is a subchart, for all possible configurations and values refer to: https://artifacthub.io/packages/helm/bitnami/minio
################################################

minio:
  enabled: true
  image:
    repository: bitnamilegacy/minio # Fix for bitnami deprecating support for their docker images https://github.com/bitnami/charts/issues/35164
  service:
    type: NodePort
    ports:
      minio: 9000
    nodePorts:
      api: "30085"
  console:
    service:
      type: NodePort
      ports:
        http: 9001
      nodePorts:
        http: "30090"
  persistence:
    enabled: true
    storageClass: "microk8s-hostpath"
    accessModes:
      - ReadWriteOnce
    size: "20Gi"
  defaultBuckets: "mlflow, flyte, raybuck"
  resources:
    limits:
      cpu: 2
      memory: "4G"
    requests:
      cpu: 2
      memory: "4G"
  nodeSelector:
    kubernetes.io/arch: "amd64"
  auth:
    rootUser: "minio"
    rootPassword: "miniostorage"

#################################################
#
# Flyte
#
# flyte-binary is a subchart, for all possible configurations and values refer to: https://github.com/flyteorg/flyte/tree/master/charts/flyte-binary
################################################

flyte-binary:
  enabled: true
  configuration:
    database:
      username: postgres
      host: postgres
      dbname: flyteadmin
    storage:
      type: minio
      metadataContainer: flyte #This is the default bucket created with Minio. Controlled by the MINIO_DEFAULT_BUCKETS env var in the local-flyte-resources.yaml manifest
      userDataContainer: flyte
      provider: s3
      providerConfig:
        s3:
          endpoint: "http://<CHANGE-ME>:30085"
          region: "us-east-1" #Irrelevant for local but still needed
          authType: "accesskey"
          accessKey: "minio"
          secretKey: "miniostorage" #If you need to change this parameters, refer to the local-flyte-resources.yaml manifest and adjust the MINIO_ROOT_PASSWORD env var
          disableSSL: "true"
          secure: "false"
    inlineSecretRef: flyte-binary-inline-config-secret
    inline:
      plugins:
        k8s:
          inject-finalizer: true
          default-env-vars:
            - FLYTE_AWS_ENDPOINT: "http://<CHANGE-ME>:30085"
            - FLYTE_AWS_ACCESS_KEY_ID: "minio"
            - FLYTE_AWS_SECRET_ACCESS_KEY: "miniostorage"
      task_resources:
        defaults:
          cpu: 1000m
          memory: 1Gi #change default requested resources and limits to fit your needs
        limits:
          memory: 2Gi
      storage:
        cache:
          max_size_mbs: 100
          target_gc_percent: 100

  serviceAccount:
    create: true

  # deployment Configure Flyte deployment specification
  deployment:
    # extraPodSpec Specify additional configuration for Flyte pod
    # This can be used for adding affinity, tolerations, hostNetwork, etc.
    extraPodSpec:
      nodeSelector:
        kubernetes.io/arch: "amd64"


#################################################
#
# prometheus-grafana
#
# kube-prometheus-stack is a subchart, for all possible configurations and values refer to: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
################################################

kube-prometheus-stack:
  fullnameOverride: "prom"
  enabled: false
  grafana:
    grafana.ini:
      security:
        allow_embedding: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

    dashboardsConfigMaps:
      default: "grafana-dashboards"