{
 "title": "Serve Dashboard",
 "tags": [ "rayVersion:2.9.1" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Application",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{}, application)"
    }
   },
   {
    "name": "HTTP_Route",
    "label": "HTTP Route",
    "query": {
     "query": "label_values(ray_serve_num_http_requests{}, route)"
    }
   },
   {
    "name": "gRPC_Method",
    "label": "gRPC Service Method",
    "query": {
     "query": "label_values(ray_serve_num_grpc_requests{}, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Utilization",
   "type": "graph",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster. Ignores application variable.",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{}) / on() (sum(autoscaler_cluster_resources{resource='GPU',}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{}) / on() (sum(ray_node_mem_total{})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{}) / on() (sum(ray_node_gram_available{}) + sum(ray_node_gram_used{})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{}) / on() sum(ray_resources{Name=\"object_store_memory\",}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{}) / on() (sum(ray_node_disk_free{}) + sum(ray_node_disk_usage{})) * 100",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "QPS per application",
   "type": "graph",
   "description": "QPS for each selected application.",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_requests{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_requests{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "Error QPS per application",
   "type": "graph",
   "description": "Error QPS for each selected application.",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_error_requests{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_error_requests{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "P50 latency per application",
   "type": "graph",
   "description": "P50 latency for selected applications.",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per application",
   "type": "graph",
   "description": "P90 latency for selected applications.",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket|ray_serve_grpc_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per application",
   "type": "graph",
   "description": "P99 latency for selected applications.",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket|ray_serve_grpc_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Replicas per deployment",
   "type": "graph",
   "description": "Number of replicas per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "QPS per deployment",
   "type": "graph",
   "description": "QPS for each deployment.",
   "gridPos": { "x": 8, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Error QPS per deployment",
   "type": "graph",
   "description": "Error QPS for each deplyoment.",
   "gridPos": { "x": 16, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "P50 latency per deployment",
   "type": "graph",
   "description": "P50 latency per deployment.",
   "gridPos": { "x": 0, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per deployment",
   "type": "graph",
   "description": "P90 latency per deployment.",
   "gridPos": { "x": 8, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per deployment",
   "type": "graph",
   "description": "P99 latency per deployment.",
   "gridPos": { "x": 16, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "graph",
   "description": "Number of requests queued per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "description": "Number of nodes in this cluster. Ignores \"Application\" variable.",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_active_nodes{}) by (NodeType)",
     "legendFormat": "Active Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_recently_failed_nodes{}) by (NodeType)",
     "legendFormat": "Failed Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_pending_nodes{}) by (NodeType)",
     "legendFormat": "Pending Nodes: {{NodeType}}"
    }
   ]
  },
  {
   "title": "Node network",
   "type": "graph",
   "description": "Network speed per node. Ignores \"Application\" variable.",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_network_receive_speed{}) by (instance)",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "sum(ray_node_network_send_speed{}) by (instance)",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  }
 ]
}